export const products = [
  {
    id: 1,
    name: 'Aroma Candle',
    price: '₹450',
    seller: 'GreenEarth',
    category: 'Home Decor',
    description: 'A natural aroma candle made with eco-friendly ingredients, perfect for relaxation and adding a warm ambiance to any room.',
    image: 'https://brownliving.in/cdn/shop/files/coconut-shell-dhoop-stickbatti-stand-wooden-incense-stick-holder-set-of-1-thenga-sustainable-candles-fragrances-brown-living-tgadhbstnd-485958_700x.jpg?v=1723850976',
  },
  {
    id: 2,
    name: 'Coconut Shell Cups (Set of 2)',
    price: '₹900',
    seller: 'EcoLife',
    category: 'Kitchenware',
    description: 'Stylish and sustainable cups made from natural coconut shells, ideal for serving beverages or as decor.',
    image: 'https://brownliving.in/cdn/shop/products/coconut-shell-cup-brown-200ml-pack-of-2-173-05695-coconut-cup-natural-handmade-tea-200-ml-set-o-cups-saucers-brown-living-109584_700x.jpg?v=1682961444',
  },
  {
    id: 3,
    name: 'Lavender Essential Oil',
    price: '₹600',
    seller: 'NatureCraft',
    category: 'Self-care',
    description: 'Pure lavender essential oil, known for its calming and relaxing properties, perfect for aromatherapy.',
    image: 'https://brownliving.in/cdn/shop/files/lavender-essential-oil-pratha-sustainable-essential-oils-brown-living-pnhpl-eoil-04-24bl8860-522354_700x.jpg?v=1727855451',
  },
  {
    id: 4,
    name: 'Yoga Bolster Made from Organic Cotton',
    price: '₹6000',
    seller: 'SustainableShop',
    category: 'Self-care',
    description: 'An ergonomic yoga bolster crafted from organic cotton for superior comfort during yoga and meditation.',
    image: 'https://brownliving.in/cdn/shop/products/yoga-bolster-made-from-organic-cotton-yo-br-r-gy-yoga-pillow-brown-living-158088_700x.jpg?v=1682970058',
  },
  {
    id: 5,
    name: 'Yoga Bolster Made from Organic Cotton (Blue)',
    price: '₹6000',
    seller: 'PureGoods',
    category: 'Self-care',
    description: 'A vibrant blue yoga bolster made from organic cotton, offering comfort and support for yoga enthusiasts.',
    image: 'https://brownliving.in/cdn/shop/products/yoga-bolster-made-from-organic-cotton-yo-br-r-nb-yoga-pillow-brown-living-690225_700x.jpg?v=1682970059',
  },
  {
    id: 6,
    name: 'Marble Coffee Tray (Set of 6)',
    price: '₹600',
    seller: 'GreenEarth',
    category: 'Home Decor',
    description: 'Elegant marble coffee tray set, perfect for serving beverages in style or as a decorative piece.',
    image: 'https://brownliving.in/cdn/shop/files/sustainable-eco-friendly-coffee-table-round-tray-by-divina-flos-at-brownliving-257718_700x.jpg?v=1731985922',
  },
  {
    id: 7,
    name: 'Handmade Terracotta Hanging Planter Duck',
    price: '₹800',
    seller: 'EcoLife',
    category: 'Home Decor',
    description: 'A charming handmade terracotta hanging planter in a duck shape, ideal for indoor or outdoor plants.',
    image: 'https://brownliving.in/cdn/shop/files/handmade-terracotta-hanging-planter-duck-kirtida-organization-sustainable-pots-planters-brown-living-11-ko-289868_700x.jpg?v=1712237947',
  },
  {
    id: 8,
    name: 'Handmade Pots',
    price: '₹800',
    seller: 'NatureCraft',
    category: 'Home Decor',
    description: 'Beautiful handcrafted pots made with sustainable materials, perfect for houseplants or as decor.',
    image: 'https://brownliving.in/cdn/shop/products/date-palm-planters-medium-fermoscapes-fsog0009-pots-planters-brown-living-773942_700x.jpg?v=1682961883',
  },
  {
    id: 9,
    name: 'Gamla',
    price: '₹580',
    seller: 'SustainableShop',
    category: 'Home Decor',
    description: 'A classic terracotta pot, ideal for growing plants and enhancing your green space.',
    image: 'https://brownliving.in/cdn/shop/products/gamla-for-plants-mud-pot-for-plants-terracotta-pots-for-plants-6-inch-pots-for-plants-pots-planters-gold-dust-brown-living-395952_400x.jpg?v=1723805265',
  },
  {
    id: 10,
    name: 'Kalimba-7 Keys',
    price: '₹1045',
    seller: 'PureGoods',
    category: 'Self-care',
    description: 'A handcrafted 7-key kalimba, perfect for creating soothing tunes and enhancing your music sessions.',
    image: 'https://brownliving.in/cdn/shop/products/kalimba-7-keys-dolphin-verified-sustainable-products-on-brown-living-526485_300x.jpg?v=1695473381',
  },
  {
    id: 11,
    name: 'Singing Bowl-Sound Therapy',
    price: '₹7245',
    seller: 'GreenEarth',
    category: 'Self-care',
    description: 'A handmade polished singing bowl, perfect for sound therapy and promoting mindfulness and relaxation.',
    image: 'https://brownliving.in/cdn/shop/products/handmade-polished-singing-bowls-for-sound-therapy-sustainable-products-on-brown-living-362454_300x.jpg?v=1688227339',
  },
  {
    id: 12,
    name: 'Linen Bedsheet',
    price: '₹750',
    seller: 'EcoLife',
    category: 'Home Decor',
    description: 'A soft, breathable, and eco-friendly linen bedsheet with a touch of elegance for your bedroom.',
    image: 'https://brownliving.in/cdn/shop/products/jaipuri-hand-printed-queen-size-cotton-yellow-bedding-set-649-verified-sustainable-products-on-brown-living-717541_700x.jpg?v=1702028864',
  },
  {
    id: 13,
    name: 'Kitchen Towel Cotton',
    price: '₹275',
    seller: 'NatureCraft',
    category: 'Kitchenware',
    description: 'Durable and absorbent cotton kitchen towel, perfect for everyday use and an eco-friendly alternative to paper towels.',
    image: 'https://brownliving.in/cdn/shop/products/multi-purpose-2-ply-kitchen-tissue-paper-roll-60-pulls-pack-of-4-rolls-the-honest-home-company-sustainable-kitchen-linens-brown-living-kt-2p-4-646049_700x.jpg?v=1709567076',
  },
  {
    id: 14,
    name: 'Wooden Ludo',
    price: '₹300',
    seller: 'SustainableShop',
    category: 'Self-care',
    description: 'A handmade wooden Ludo board game for hours of fun, perfect for kids and adults alike.',
    image: 'https://brownliving.in/cdn/shop/products/handmade-wooden-ludo-travel-board-game-for-kids-and-adult-ortus-arts-sustainable-learning-educational-toys-brown-living-1306-730544_700x.jpg?v=1709219591',
  },
  {
    id: 15,
    name: 'Wooden Chess',
    price: '₹500',
    seller: 'PureGoods',
    category: 'Self-care',
    description: 'A handcrafted wooden chess set, combining classic gameplay with eco-friendly materials.',
    image: 'https://brownliving.in/cdn/shop/products/wooden-chess-board-game-white-light-elements-sustainable-learning-educational-toys-brown-living-436520_300x.jpg?v=1708589179',
  },
  {
    id: 16,
    name: 'Spice Box-Wooden Set (3x3)',
    price: '₹859',
    seller: 'GreenEarth',
    category: 'Kitchenware',
    description: 'A stylish and functional wooden spice box with multiple compartments for organizing your spices.',
    image: 'https://brownliving.in/cdn/shop/files/sustainable-sheesham-wood-8-compartment-spice-holder-by-organic-b-at-brownliving-863266_700x.jpg?v=1731617311',
  },
  {
    id: 17,
    name: 'Handcrafted Wooden Serving Tray',
    price: '₹1200',
    seller: 'ArtisanCraft',
    category: 'Kitchenware',
    description: 'A beautifully handcrafted wooden serving tray, perfect for serving meals or as a decorative piece.',
    image: 'https://exclusivelane.com/cdn/shop/products/el-005-321_a_1800x1800.jpg?v=1570516271',
  },
  {
    id: 18,
    name: 'Eco-friendly Recycled Notebook',
    price: '₹250',
    seller: 'Rescript',
    category: 'Self-care',
    description: 'A compact and stylish notebook made from recycled materials, ideal for notes and journaling.',
    image: 'https://www.rescript.in/assets/uploads/inventory/pro_63d8d7365a5212556.jpg',
  },
  {
    id: 19,
    name: 'Bamboo Toothbrush Set',
    price: '₹350',
    seller: 'GreenEarth',
    category: 'Self-care',
    description: 'A set of biodegradable bamboo toothbrushes with activated charcoal bristles, promoting dental hygiene sustainably.',
    image: 'https://www.bigbasket.com/media/uploads/p/l/40220415-7_1-bamboooz-bamboo-toothbrush-with-activated-charcoal-bristles-straight-grip-72-cm-eco.jpg',
  },
  {
    id: 20,
    name: 'Sustainable Water Bottle (500ml)',
    price: '₹650',
    seller: 'PureGoods',
    category: 'Self-care',
    description: 'A durable and eco-friendly water bottle made with bamboo and stainless steel, keeping beverages hot or cold for hours.',
    image: 'https://brownliving.in/cdn/shop/products/bamboo-stainless-steel-bottle-vaccum-insulated-double-wall-hot-cold-500ml-sustainable-products-on-brown-living-247182_600x600_crop_center.jpg?v=1688224999',
  },
];
